In [27]:
import numpy as np

In [28]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [29]:
arr+1

array([2, 3, 4, 5, 6, 7])

In [30]:
arr-1

array([0, 1, 2, 3, 4, 5])

In [31]:
arr*5

array([ 5, 10, 15, 20, 25, 30])

In [32]:
print (arr%1)

[0 0 0 0 0 0]


In [33]:
print (arr**2)

[ 1  4  9 16 25 36]


In [34]:
arr=np.array([1,2,3,4,5,6])
print (arr)

[1 2 3 4 5 6]


In [35]:
arr=arr+1
print (arr)

[2 3 4 5 6 7]


In [36]:
arr +=1
arr

array([3, 4, 5, 6, 7, 8])

In [38]:
arr.max() #the max function

16

In [41]:
arr=np.array([[1,2,3],

            [4,5,6],
            [7,8,9]])
print (arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
arr.max(axis=0) # max element column wise

array([7, 8, 9])

In [44]:
arr.max(axis=1) # max element row wise

array([3, 6, 9])

In [45]:
arr.min(axis=0)

array([1, 2, 3])

In [46]:
arr.sum()

45

In [47]:
arr=+1
print (arr)

1
