In [1]:
import numpy as np


In [2]:
marr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [8, 7, 6, 5], [4, 3, 2, 1]])
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])


In [9]:
print(arr)


[1 2 3 4 5 6 7 8]


In [12]:
arr[:-3]


array([1, 2, 3, 4, 5])

In [13]:
arr[3:-3]

array([4, 5])

In [15]:
marr[:,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [17]:
marr[:1,:]

array([[1, 2, 3, 4]])

In [21]:
marr[2:,:]

array([[8, 7, 6, 5],
       [4, 3, 2, 1]])

In [30]:
marr[3:,1:2]

array([[3]])

In [31]:
marr[1:,1:]

array([[6, 7, 8],
       [7, 6, 5],
       [3, 2, 1]])