In [1]:
import numpy as np

In [3]:
arr=np.array([[7,3,8,6,4],[7,2,9,8,6],[5,4,2,3,1]])
print (arr)

[[7 3 8 6 4]
 [7 2 9 8 6]
 [5 4 2 3 1]]


In [5]:
np.sort(arr,axis=1,kind='mergesort') # row wise sort

array([[3, 4, 6, 7, 8],
       [2, 6, 7, 8, 9],
       [1, 2, 3, 4, 5]])

In [7]:
np.sort(arr,axis=0,kind='mergesort') # column wise sort


array([[5, 2, 2, 3, 1],
       [7, 3, 8, 6, 4],
       [7, 4, 9, 8, 6]])

In [8]:
np.sort(arr,kind='mergesort') # default is row wise sort


array([[3, 4, 6, 7, 8],
       [2, 6, 7, 8, 9],
       [1, 2, 3, 4, 5]])