In [1]:
import numpy as np

In [8]:
lst=[[1,2,3],
[1,2,3]]
lst

[[1, 2, 3], [1, 2, 3]]

In [10]:
type(lst)

list

In [12]:
arr=np.array(lst)
arr


array([[1, 2, 3],
       [1, 2, 3]])

In [5]:
type(arr)

numpy.ndarray

In [13]:
arr.ndim

2

In [14]:
arr.shape

(2, 3)

In [15]:
arr.size

6

In [16]:
arr.dtype

dtype('int32')

In [20]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])