In [2]:
import numpy as np

In [19]:
arr=np.random.random((4,3)) #the range is always from 0 to 1

In [12]:
if np.random.random() > 0.5:
    print ("Run the function")
else:
    print("Don't Run it")

Run the function


In [14]:
np.arange(1,10,2) #starting condition , ending condition, difference between values

array([1, 3, 5, 7, 9])

In [17]:
np.linspace(1,7,10) #starting condition , ending condition, how many values you want within the range

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        , 5.66666667, 6.33333333, 7.        ])

In [20]:
arr

array([[0.32371493, 0.18475833, 0.7046443 ],
       [0.45510446, 0.61483793, 0.27435341],
       [0.47965614, 0.51365798, 0.57598589],
       [0.83521925, 0.03603445, 0.11452917]])

In [21]:
arr=np.reshape(arr,(3,4))

In [22]:
arr

array([[0.32371493, 0.18475833, 0.7046443 , 0.45510446],
       [0.61483793, 0.27435341, 0.47965614, 0.51365798],
       [0.57598589, 0.83521925, 0.03603445, 0.11452917]])

In [24]:
arr=np.reshape(arr,(6,2))
arr # the size i.e. row x col should be same to reshape an array here 6*2=12 similarly 3*4=12

array([[0.32371493, 0.18475833],
       [0.7046443 , 0.45510446],
       [0.61483793, 0.27435341],
       [0.47965614, 0.51365798],
       [0.57598589, 0.83521925],
       [0.03603445, 0.11452917]])